### ISSUE TITLE
Unable to get the IntendedFor field to populate on fieldmaps.

### ISSUE THREAD

**Issue by Michael-Monaldi** [Donders-Institute/bidscoin#102]
We are unable to get the IntendedFor field to populate on fmaps.
This happens on 3.6.3 stable and on 3.7.0dev
I have used the following in the bidsmap_dccn.yaml

bold
\*bold*
\<bold>
\<\<bold>>
\<\*bold*>
\<\<\*bold*>>

All the above variants, using the word "task"
\<\<task-*bold>>

The IntendedFor ends up being either:
what was literally typed including the "< and>" characters, or
IntendedFor : null

_Originally posted by @Michael-Monaldi in https://github.com/Donders-Institute/bidscoin/issues/92#issuecomment-887073114_

**Comment by marcelzwiers** [comment]
The intendedfor cannot be updated by the bidsmapper (as the data isn't
there yet), that happens during bidscoiner runtime. Is that what you see?

_____________________
Sent from my phone

Op di 27 jul. 2021 01:11 schreef Michael-Monaldi ***@***.***>:

**Comment by marcelzwiers** [comment]
In other words, did you check the JSON files or are you looking at the
study bidsmap?

_____________________
Sent from my phone

Op di 27 jul. 2021 01:11 schreef Michael-Monaldi ***@***.***>:

**Comment by Michael-Monaldi** [comment]
I saw you had changed the dcm2bidsmap plugin to be incorporated in the dcm2niix2bids plugin earlier.
Did a pip force-reinstall, now it works.
It was previously populating to "null" in the JSONS.

Now that it is working, what would be the proper syntax in future?
Are the leading and trailing wildcards truly implicit and unnecessary?
When are single and double angle brackets required and not required?

I am only specifically asking because it was not behaving as docs and the prior referenced issue described...
Thanks!

**Comment by marcelzwiers** [comment]
True, the github version is under constant development and the docs are in sync with the released versions. Was the IntendedFor broken in the released version? Because then I'd like to fix that. FYI, I am about to submit a bidscoin paper that will explain the working and design in more detail, and would like to release bidscoin 3.7 along with the paper. Here's a snippet about the dynamic values that you may find useful:
> 2.2.2	Dynamic values
In a bidsmap, the BIDS-mappings are hierarchically grouped in BIDS datatypes, such as `anat`, `dwi` and `func`, and accompanied with a `subject` and a `session` key-value pair (Figure 2). The values of these latter two contain the BIDS subject and session labels, albeit not statically but dynamically, i.e. the actual label will be extracted from the data during runtime. Bidsmap values can be made ‘dynamic’ by putting a data attribute or property key between single (<>) or double brackets (<<>>). Single brackets will always be extracted directly by BIDScoin routines and are typically part of a template bidsmap. Hence, When the template bidsmap is converted to a study bidsmap, they are extracted and presented to the user for further editing. For instance {acq: <ProtocolName>} in the bids output dictionary of the template bidsmap will show up as {acq: t1mpragesagp2iso10} in the study bidsmap (Figure 2). Double bracket dynamic values will remain to be present in the study bidsmap and will only be extracted during (bidscoiner) runtime. Single bracket dynamic values are therefore most useful as an intelligent guess for output dictionary values that vary only between datatypes, whereas the double bracket values can be useful for dictionary values that vary more often, such as between subjects, sessions or runs of the same datatype. For instance, the value {Comments: <<PatientComments>>} in the meta dictionary (Figure 2) will extract the comments for that specific subject or session and the value {subject: <<filepath:/sub-(.*?)/>>}  will extract ‘003’ (i.e. the shortest string between `/sub-` and `/`) if the data for that subject is in ‘/data/raw/sub-003/ses-01’. The latter example illustrates how a colon-separated regular expression can be appended to the ‘filepath’ or ‘filename’ property keys to extract a substring, as researchers often encode multiple values or key-value pairs in a single filepath or filename.
> The dynamic values can handle many use cases and can be used throughout BIDScoin. Yet there are two dynamic values in the output dictionaries that required special treatment. The first one is the `run` index in the bids dictionary. If this is a number (e.g. {run: <<1>>}) and an output file with that run-index already exists, then this number will be incremented in compliance with the BIDS standard (e.g. to {run: 2}). The other special dynamic value is the `IntendedFor` value in the meta dictionary. The IntendedFor values are used in BIDS to semantically indicate for which images the fieldmap was acquired. The user can specify this using Unix shell-style wildcards, which will be used by the bidscoiner routine to lookup these images on disk. For instance, using {IntendedFor: <<task>>} will select all functional runs in the BIDS subject[/session] folder (since these runs always have ‘task’ in their filename), and using {IntendedFor: <<Stop*Go><Reward>>} will select all “Stop1Go”-, “Stop2Go”- and “Reward”-runs.

**Comment by marcelzwiers** [comment]
Oh, and to answer your questions:
> I saw you had changed the dcm2bidsmap plugin to be incorporated in the dcm2niix2bids plugin earlier.
Yes, initially I splitted it to make it as modular as possible, but now I changed my mind because I figured that nobody will use that and it probably only causes confusion.

> Did a pip force-reinstall, now it works. It was previously populating to "null" in the JSONS.
I see, so the latest released version works I guess, good.

> Now that it is working, what would be the proper syntax in future? Are the leading and trailing wildcards truly implicit and unnecessary? When are single and double angle brackets required and not required?
I hope the snippet above helps?

> I am only specifically asking because it was not behaving as docs and the prior referenced issue described...
Yes, keep in mind that the docs by defaults go to the released / stable version, not to the latest, i.e. it goes to:

https://bidscoin.readthedocs.io/en/stable/

But not to:

https://bidscoin.readthedocs.io/en/latest/
