### ISSUE TITLE
Python KeyError when a run-item doesn't much any rule

### ISSUE THREAD

**Issue by mateuszpawlik** [Donders-Institute/bidscoin#106]
While testing my map file on a new dataset I experienced the following Python KeyError:
```
  File "/usr/local/lib/python3.9/dist-packages/bidscoin/bidseditor.py", line 459, in update_subses_samples
    if run['bids']['suffix'] in bids.get_derivatives(datatype):
KeyError: 'suffix'
```
It comes from [line 459](https://github.com/Donders-Institute/bidscoin/blob/d66d7c1092788ac41d0354156673c4b8df152d00/bidscoin/bidseditor.py#L459).

My guess is that the error happens because some of my sequences don't match any rule. Could that be the case?

I think this corresponds to #97. The bidsmapper assumes certain behavior based on the information in your dccm template map file. However, if one writes the template map from scratch, it is not clear what should be included.

Such errors should be caught and reported, saying for example "Run-item 002-AAHead_Scout doesn't match any rule in your template.".

**Comment by marcelzwiers** [comment]
Thanks for reporting, I added a few lines (6b1a19ada6e8647e7a6a7b6a6ceb20891b1bd1b0) so that the bidseditor hopefully doesn't crash anymore. But proper bidsmap checking is done when loading the bidsmap, so I didn't add new warnings in the bidseditor (the bidseditor should just edit the bidsmap, in whatever form it is)

**Comment by marcelzwiers** [comment]
I'm closing this issue, but please re-open it if the problem persists
