### ISSUE TITLE
Automatic task name extraction from DICOM field

### ISSUE THREAD

**Issue by mateuszpawlik** [Donders-Institute/bidscoin#107]
What could be the way to extract automatically the task name from, for example, the SeriesDescription DICOM field? For example, the SeriesDescription is `fmri_taskname_otherstuff` and I'd like only the `taskname` to be extracted.

Correct me if I'm wrong but currently, for each different task name a single run-item has to be written in the map file.

If generalized, would such a functionality fit bidscoin?

**Comment by marcelzwiers** [comment]
I thought about this and, since at the DCCN we generally would just edit the `fmri_taskname_otherstuff` to `taskname` per study with the bidseditor (the SeriesDescription field isn't used consistently in the DCCN), I left it until needed. In the upcoming BIDScoin version (3.7), I did implement a similar functionality for the `filepath` and `filename` properties. There I used a colon to add a regular expression to the key. In that way, part of the value can be extracted, just like you described. For instance, the value {subject: <<filepath:/sub-(.*?)/>>}  will extract {subject: ‘003’} (i.e. '003' = the shortest string between `/sub-` and `/`) if the data for that subject is in `/data/raw/sub-003/ses-01`. Do you have a use case where you are getting a long list run-items with different task names?

**Comment by mateuszpawlik** [comment]
> In the upcoming BIDScoin version (3.7), I did implement a similar functionality for the filepath and filename properties. There I used a colon to add a regular expression to the key. In that way, part of the value can be extracted, just like you described. For instance, the value {subject: <filepath:/sub-(.*?)/>} will extract {subject: ‘003’} (i.e. '003' = the shortest string between /sub- and /) if the data for that subject is in /data/raw/sub-003/ses-01.

I think that would work well. Is there a simple way to add this feature?

> Do you have a use case where you are getting a long list run-items with different task names?

I'm currently working on converting many (initially 15) older fmri datasets to BIDS. BIDScoin suits well when it comes to reviewing the conversion. Though, I'd like to automatize the process a bit. Many studies used names like `fmri_somename` for the `SeriesDescription` which would allow me to extract the task name. Studies that used names like `fmri_1` I can't automatize anyways.

We're also considering to use BIDScoin for converting new incoming data which would not require user interaction.

**Comment by marcelzwiers** [comment]
I see. Well, I can implement it quite easily I think, I'll give it a try

**Comment by marcelzwiers** [comment]
Done (see: bd44495d907065620012dd051299b2a276208616)! You can use / test this pre-release code with:

`pip install --upgrade git+https://github.com/Donders-Institute/bidscoin`

And then use something like:

task: <SeriesDescription:fmri_(.*?)_>

Let me know if it doesn't work for you as you would like :-)

**Comment by mateuszpawlik** [comment]
It was really quick. Thank you. It works as expected.

You reminded me about #99. Sorry for not submitting yet.

**Comment by AlexanderFrotscher** [comment]
> Done (see: [bd44495](https://github.com/Donders-Institute/bidscoin/commit/bd44495d907065620012dd051299b2a276208616))! You can use / test this pre-release code with:
> 
> `pip install --upgrade git+https://github.com/Donders-Institute/bidscoin`
> 
> And then use something like:
> 
> `task: <SeriesDescription:fmri_(.*?)_>`
> 
> Let me know if it doesn't work for you as you would like :-)

Hey,

I want to do the same thing as [mateuszpawlik](https://github.com/mateuszpawlik) and use bidscoin to bring some data sets into BIDS format. This approach should also be automated and currently I get the error for my functional data that the task value is missing. Similar to his data sets the task is written in the filename. I see that you already answered how it is possible to extract that task name, but I am unable to replicate this ( because I am not informed, skilled, enough). Where do I need to use task: <SeriesDescription:fmri_(.*?)_> ? In this bidsmap that I am using? I put it to
func:
provenance:
properties:
attributes:
bids:
task: I put it right here

And I did this for the nibabel and dicom fields in the map for func. Did I get something completly wrong? Thank you for your patience.

**Comment by mateuszpawlik** [comment]
Your pattern `<SeriesDescription:fmri_(.*?)_>` will extract the substring from `SeriesDescription` value between `fmri_` and the next `_` and assign it as the task value. What is your `SeriesDescription` value? Could you also send the relevant excerpt of your bidsmap?

**Comment by marcelzwiers** [comment]
Maybe, as an example use case, it can be useful to have a look at the `bidsmap_bids2bids` file:

https://github.com/Donders-Institute/bidscoin/blob/master/bidscoin/heuristics/bidsmap_bids2bids.yaml

**Comment by AlexanderFrotscher** [comment]
Thanks to both of you for the quick reply. I was able to solve my problem by having a look at the bids2bids map.
