### ISSUE TITLE
Scrolling crashes the edit window

### ISSUE THREAD

**Issue by marcelzwiers** [Donders-Institute/bidscoin#20]
When scrolling the edit window you can crash the interface and get this error:

Traceback (most recent call last):
  File "/home/mrphys/marzwi/python/bidscoin/bidscoin/bidseditor.py", line 843, in selection_dropdown_change
    self.target_suffix = self.allowed_suffixes[self.target_modality][0]
IndexError: list index out of range

**Comment by rutgervandeelen** [comment]
This crash is caused when the `allowed_suffixes` variable has empty lists for `anat`, `dwi`, `func`. This situation should not occur when the default template in `./heuristics/bidsmap_template.yaml`  is used. 

In `bidseditor.py` I have changed the code from
```
# Obtain the initial bidsmap info
template_bidsmap = bids.load_bidsmap(templatefile, os.path.join(bidsfolder,'code'))
```
to
```
# Obtain the initial bidsmap info
template_bidsmap = bids.load_bidsmap(templatefile, None)
```
so that the bidsmap template `./heuristics/bidsmap_template.yaml` is used. See commit fb3601b18009808a239a2193241d1323b39a84fd
