### ISSUE TITLE
KeyError: 'bidscoin' using bidscoin in Neurodesk

### ISSUE THREAD

**Issue by iishiishii** [Donders-Institute/bidscoin#249]
**Describe the bug**
I wanted to open the editor GUI for bidscoin 4.4.0 from the terminal but got this error while earlier version works alright:

```
Creating BIDScoin user configuration:
-> /home/jovyan/.bidscoin/4.4.0/config.toml
-> /home/jovyan/.bidscoin/4.4.0/plugins/dcm2niix2bids.py
-> /home/jovyan/.bidscoin/4.4.0/plugins/spec2nii2bids.py
-> /home/jovyan/.bidscoin/4.4.0/plugins/nibabel2bids.py
-> /home/jovyan/.bidscoin/4.4.0/templates/bidsmap_dccn.yaml
-> /home/jovyan/.bidscoin/4.4.0/templates/bidsmap_bids2bids.yaml
-> /home/jovyan/.bidscoin/4.4.0/templates/bidsmap_sst.yaml
-> /home/jovyan/.bidscoin/4.4.0/templates/schema.json
INFO | 
INFO | -------------- START BIDSeditor ------------
INFO | >>> bidseditor bidsfolder=/home/jovyan/neurodesktop-storage bidsmap=bidsmap.yaml template=/home/jovyan/.bidscoin/4.4.0/templates/bidsmap_dccn.yaml
INFO | Reading: /home/jovyan/.bidscoin/4.4.0/templates/bidsmap_dccn.yaml
INFO | generated new fontManager
INFO | Checking the bidsmap run-items:
INFO | No bidsmap file found: /home/jovyan/neurodesktop-storage/code/bidscoin/bidsmap.yaml
SUCCESS | All datatypes and options in the template bidsmap are valid
Traceback (most recent call last):
  File "/opt/miniconda-latest/bin/bidseditor", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/miniconda-latest/lib/python3.12/site-packages/bidscoin/bidseditor.py", line 2036, in main
    raise error
  File "/opt/miniconda-latest/lib/python3.12/site-packages/bidscoin/bidseditor.py", line 2032, in main
    bidseditor(**vars(args))
  File "/opt/miniconda-latest/lib/python3.12/site-packages/bidscoin/bidseditor.py", line 2005, in bidseditor
    if input_bidsmap.options:
       ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda-latest/lib/python3.12/site-packages/bidscoin/bids.py", line 1008, in options
    return self._data['Options']['bidscoin']
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'bidscoin'
```

**To reproduce**
1. Go to Terminal
2. Run `bidseditor neurodesktop-storage/`
3. See error

**Expected behavior**
It should open the main window of the bidseditor.

**Software version**
 - BIDScoin version 4.4.0
 - OS: Linux

**Additional context**
I ran this from Neurodesk.

**Comment by marcelzwiers** [comment]
You are right, it's a bug that happens when you pass a bids folder to the bidseditor that doesn't contain a bidsmap. The bidseditor should (and did in the past) open a file dialogue window, for you to select a bidsmap to edit. I could reproduce this issue with bidscoin 4.4.0, but it happens to be fixed already in the latest development code (see [here](https://github.com/Donders-Institute/bidscoin/blob/ab90a17cc2ccbceaa42e1a893437a633e4c01685/bidscoin/bidseditor.py#L2264)). And it is a bit of a rare use case (editing a bidsfolder with no bidsmap) that does not hinder regular bidsmapper -> bidseditor workflows. I am therefore closing this issue, but thanks a lot for reporting, it's appreciated!
