### ISSUE TITLE
dcm2niix link dosn't work

### ISSUE THREAD

**Issue by MCaviezel** [Donders-Institute/bidscoin#43]
Hi,

I used an Anaconda environment to run bidscoin.
I installed dcm2niix via conda and bidscoin via pip install in this environment.
I can run bidsmapper without a problem.
If I go to the obtions to test bidscoin it tells me:
BIDS-version: 1.1.0
BIDScoin-version: 2.2

The dcm2niix test is by default:
module add dcm2niix;

If I test this I the following error:
Failed to run module add dcm2niix;dcm2niix -h (errorcode 0)
I can change the path to "...anaconda3/envs/BIDS/bin/" where the dcm2niix file is located and then it passes the test.
Then I save this "bidsmap.yaml" file and try to run bidscoiner.py and get an error, which then doesn’t work.
The error message is attached.

Is the a possibility to solve this issue?

Thanks for your help,

Marco

[bidscoiner_error.txt](https://github.com/Donders-Institute/bidscoin/files/3502303/bidscoiner_error.txt)

**Comment by marcelzwiers** [comment]
Hi Marco,

* You do not seem to have / use the environment module system (https://modules.readthedocs.io/en/latest/), which is what we use at the Donders. But that is no problem, you solved it correctly by setting the path to dcm2iix
* The bidsmap.yaml error that you get from the bidseditor is a known issue (see e.g. #41) and it is caused by flaws in the ruamel.yaml library that I use to read/write yaml files. You can upload the yaml file to a yaml-validator (e.g. to www.yamllint.com/) and then you will probably see that there are some erroneous line-breaks somewhere (you can manually correct them, and then bidscoiner should work). What version of ruamel.yaml are you using? Perhaps upgrading to the latest version would help... Can you run `pip search ruamel.yaml` for me?

**Comment by marcelzwiers** [comment]
p.s. I plan to release a new version of BIDScoin in the coming days / week, which may also mitigate the ruamel problem...

**Comment by MCaviezel** [comment]
Hi Marcel,

Thanks for your quick reply!
With the yaml-validator I figured out that this problem was due to the Plugins section in the bidsmap file. When using bitmapper.py, I used the bidsmap_dccn.yaml as a template since I needed the same specifications as you do, but this leads to this error.

Now, I have the following problems:
1.) I'm using Siemens fieldmaps:
In the first fieldmap dicom folder I'm getting two two magnitude images with different echo times and one fieldmap dicom folder with the phasediff image.
If I apply the bitmapper, it only recognizes one of the two magnitude image.
I attached the bidsmap.yaml (with as .txt to upload it on github) , log and error files.

[with_fieldmap_bidscoiner_errors.log](https://github.com/Donders-Institute/bidscoin/files/3505123/with_fieldmap_bidscoiner_errors.log)
[with_fieldmap_bidscoiner.log](https://github.com/Donders-Institute/bidscoin/files/3505124/with_fieldmap_bidscoiner.log)
[with_fieldmap_traceback_fieldmap_error.txt](https://github.com/Donders-Institute/bidscoin/files/3505125/with_fieldmap_traceback_fieldmap_error.txt)
[with_fieldmap_bidsmap.yaml.txt](https://github.com/Donders-Institute/bidscoin/files/3505132/with_fieldmap_bidsmap.yaml.txt)

2.) If I don't use the field maps, it converts all scans except the MPRAGE and one of three scanns. The error says: "Unkown run detected:"
I also attached the bidsmap.yaml, log and error files.

[withtout_fieldmap_bidscoiner_errors.log](https://github.com/Donders-Institute/bidscoin/files/3505127/withtout_fieldmap_bidscoiner_errors.log)
[withtout_fieldmap_bidscoiner.log](https://github.com/Donders-Institute/bidscoin/files/3505128/withtout_fieldmap_bidscoiner.log)
[withtout_fieldmap_bidsmap.yaml.txt](https://github.com/Donders-Institute/bidscoin/files/3505133/withtout_fieldmap_bidsmap.yaml.txt)

Are some of these issues known and is there a way to fix them?
I'm very grateful for your help!

Best,
Marco

**Comment by marcelzwiers** [comment]
Hi Marco,

With the yaml-validator I figured out that this problem was due to the
> Plugins section in the bidsmap file. When using bitmapper.py, I used the
> bidsmap_dccn.yaml as a template since I needed the same specifications as
> you do, but this leads to this error.
>
 Interesting, since the two templates are essentially the same (except for
the content). What ruamel version do you use?

1.) I'm using Siemens fieldmaps:
> In the first fieldmap dicom folder I'm getting two two magnitude images
> with different echo times and one fieldmap dicom folder with the phasediff
> image.
> If I apply the bitmapper, it only recognizes one of the two magnitude
> image.
>
I believe you have run into a bug I squashed in the unreleased code. The
current code on github is running quite stably, could you perhaps try that
using:

pip install --upgrade git+https://github.com/Donders-Institute/bidscoin

I) attached the bidsmap.yaml (with as .txt to upload it on github) , log
> and error files.
>
>
> <https://github.com/Donders-Institute/bidscoin/files/3505123/with_fieldmap_bidscoiner_errors.log>2)
> If I don't use the field maps, it converts all scans except the MPRAGE and
> one of three scanns. The error says: "Unkown run detected:"
>
Don't forget that the template_dccn only makes suggestions for the modality
(e.g. anat -> T1), but you should always make sure it is correct (if not,
change it)

Best,
Marcel

**Comment by marcelzwiers** [comment]
Maybe you need to reinstall instead of upgrade, I'm not sure

**Comment by MCaviezel** [comment]
Hi Marcel,

Thanks again for your quick help!
I reinstalled bidscoin and now everything runs without errors in version 2.3.
This is great!!!
I only get one warning:

"WARNING Missing Echo-Time data for: /.../bids/sub-002/ses-SourceFilePath/fmap/sub-002_ses-SourceFilePath_acq-B0fieldmap_run-1_phasediff.json"

In the json file of the phasediff image it says:

    "EchoTime1": null,
    "EchoTime2": null

Is it possible to enter this parameter in the bidseditor or shall I enter this information manually?

Best,
Marco

**Comment by MCaviezel** [comment]
I forgot to mention that I use ruamel.yaml (0.16.1)

**Comment by MCaviezel** [comment]
I just fixed it by selecting "Magnitued 1" instead of "Magnitude".
Then everything works smoothly!
Thank you very much for your efforts!
It's an amazing tool!

**Comment by marcelzwiers** [comment]
> I reinstalled bidscoin and now everything runs without errors in version 2.3.
> This is great!!!
Good to hear :-)

> I only get one warning:
> 
> "WARNING Missing Echo-Time data for: /.../bids/sub-002/ses-SourceFilePath/fmap/sub-002_ses-SourceFilePath_acq-B0fieldmap_run-1_phasediff.json"
> 
> In the json file of the phasediff image it says:
> 
> ```
> "EchoTime1": null,
> "EchoTime2": null
> ```
I have had this before and thought I squashed it. It can have two causes:
1. dcm2niix doesn't recognize the TE in the magnitude1 and magnitude2 images
2. The bidscoiner failes to collect the TE's
Could you perhaps check whether the TE's are correct in the magnitude1.json and magnitude2.json files?

> Is it possible to enter this parameter in the bidseditor or shall I enter this information manually?
Sorry, that is not possible

**Comment by marcelzwiers** [comment]
> I just fixed it by selecting "Magnitued 1" instead of "Magnitude".
> Then everything works smoothly!

That is intended behaviour as this is how the BIDS specifications prescribe fieldmaps (magnitude1 + magnitude2 + phasediff for e.g. Siemens fieldmaps)

> Thank you very much for your efforts!
> It's an amazing tool!

:-)

**Comment by amhaun01** [comment]
Hello, I'm trying to get this BIDScoin tool to work, and I am hung up immediately on the step that was the issue in this thread (https://github.com/Donders-Institute/bidscoin/issues/43)

testing fails on:
`2022-05-25 15:47:13 - INFO | --------- Testing the 'dcm2niix2bids' plugin ---------
2022-05-25 15:47:13 - INFO | Succesfully imported 'dcm2niix2bids'
2022-05-25 15:47:13 - INFO | Testing the dcm2niix2bids installation:
2022-05-25 15:47:13 - INFO | Running: module add dcm2niix; dcm2niix -u; module add dcm2niix; dcm2niix
2022-05-25 15:47:13 - ERROR | Failed to run:
module add dcm2niix; dcm2niix -u; module add dcm2niix; dcm2niix
Errorcode 0:`

I see something about "changing path" in the comments and above, but I don't understand what to do (what is "module add" etc).

dcm2niix is there and I can call it from command line, use it through matlab etc:
`(mri) andrews-imac:~ amhaun01$ which dcm2niix
/Users/amhaun01/miniconda3/envs/mri/bin/dcm2niix`

thanks for any help
-andrew

**Comment by marcelzwiers** [comment]
Sorry to hear that the path / module system was confusing. Within python it is a bit complicated to install non-Python binaries, such as from dcm2niix. That's why you have to set the path to this binary yourself, so that your operating system is able to find and execute it. In Linux, this can e.g. be done with a `module add dcm2niix` call, in Windows you can remove that part and add the path where you saved your dcm2niix binary. See here for more info:

* https://bidscoin.readthedocs.io/en/stable/installation.html#dcm2niix-installation
* https://bidscoin.readthedocs.io/en/stable/options.html 

Let me know if you still experience problems
