### ISSUE TITLE
New project based on bidscoin

### ISSUE THREAD

**Issue by nbeliy** [Donders-Institute/bidscoin#54]
Hi all,

I was tasked to adapt the bidscoin to the needs to my laboratory. As the changes was quite significant,
I transformed bidscoin into more object oriented code (which is in theory more flexible). The readme files and licences are not changed, I will work on it next week.

I've put code in https://github.com/nbeliy/bidscoin, and example dataset 
with all needed files in https://github.com/nbeliy/bidscoin_example

1. So, would you be interested in participating in further development of it?
2. Can I use the name `bidscoin2`? I would like to conserve bidscoin, as it follows the same logic and progression as your code, but interface and structure is changed considerably.

Main changes:
 - Main class `Module` define an interface between bidscoin and different images formats
 - Module daughter `MRI` define global MRI image characteristics (like list of modalities, JSON fields, bids entities etc...)
 - Module grand-daughter `Nifti_SPM12` defines how nifti files converted by SPM12 should be treated (it is just nii with dumped json file)
 - Overall, daughter of Module defines BIDS propriety for specifics types of images, and grand-daughter defines how individual formats of given type are treated 
 - yaml file mirror this structure
 - Individual runs contains `json` dictionary for additional entries for json sidecar files
 - Matching strings for attributes supports regexp (they just passed to re)
 - `get_dynamic_field` with double brackets supports prefixes, for example `<<bids:task>>` will retrieve value of `task` entity   
 - The intermediary step of sorting files now becomes mandatory together with sub and ses prefixes
 - Improved support of plugins which is called at various points of coinage, making it more flexible
 - The conversion of files is removed: the conversion tools are too versatile and laboratory dependent
 - The GUI dissapeared (It took me too much time to adapt it), but is in plans
  

Cheers,
Nikita

**Comment by marcelzwiers** [comment]
Hi Nikita,

I have thought about making bidscoin more object oriented, e.g. by making a bidsmap class, probably similar to what you have been doing. I would be very much interested in working together and keeping a single code base, rather than forking it to bidscoin2. I am curious to know what the limitations were in my original implementation that made you transform it. If you are interested in further developing bidscoin together, perhaps we can sit down together to merge the two branches?

Cheers,
Marcel

**Comment by nbeliy** [comment]
Hi Marcel,

The main problem was the file format -- we use Nifty with dump of header into json file. At first I tried to implement your pre-defined functions, but I realized that in majority of cases you hardcode your source variable to be DICOM. Also the conversion of dicom to nii is forced in your code, which isn't situable of my dataset (we use SPM12 hMRI toolset to do the conversion). So there was a lot of adaptation all through your code, and rendering it with virtual classes was just easier. Also we use extensively the EEG, so the hardcoded recording bids entities and attributes could pose some problems.

The rest is just reorganization of code (in order to evoid large files), and incorporating my libraries for treating bids tsv files and plugins. 

I don't think that merge two branches will be a good idea -- the interface changed too much, and your map files will not be compatible. It could be dangerous for people who already use bidscoin: after pull everything will stop working. But we can try.

IMHO, the best course of action is that you read the code in diagonal and see if it still follows the bidscoin as you imagined it. If it does we can merge (and implement the DICOM part, it will be a good test for virtual classes). 

Cheers,
Nikita

**Comment by marcelzwiers** [comment]
I see, I didn't implement nifti input yet, but I designed bidscoin such that it would go over different passes (don't know if that was a good idea). So the first pass would do DICOM to nifti (but you could skip this by making the bidsmap.DICOM empty), then a second pass for PAR/REC, then a third pass for nifti. The placeholder functions were there, but never implemented. When I have a bit more time I will have a closer look at your code

**Comment by nbeliy** [comment]
The problem is, it's not just nifty generic, but with exported header, with a particular structure. So in order to implement, I must put an additional elif in order to not interfere with a generic nifty.

I copied your if/elif structure in my code in Modules/selector.py, where I define a dictionary of formats, and in the loop select the one that works. So once a new format is introduced, it will be enough to add corresponding class into dictionary.

**Comment by marcelzwiers** [comment]
I had a closer look and I agree with you that the changes you made are quite significant. Your project looks very interesting and of high code quality, but I also think it has moved in a different direction that is a bit beyond my area of expertise and possibly not so much in the interest of the local users I support over here. I don't really have the time to rework your code so that it will work again locally, so I prefer to keep further developing my own branch. But who knows, one day...

I think the name bidscoin2 suggests that it is the successor of bidscoin, but it really is a fork. So, although you are of course free to chose any name, I would be more happy if that name would be a different name that doesn't imply being the bidscoin successor.

**Comment by nbeliy** [comment]
No problem, but renaming could take some time
