### ISSUE TITLE
bidseditor does not support multiple echoes for anat

### ISSUE THREAD

**Issue by dangom** [Donders-Institute/bidscoin#62]
Hi Marcel,

I've looked into bidscoin earlier today and played a bit with it, and I was positively surprised on how much it has grown and how easy it is to use!

Nonetheless, I noticed that for the data I was trying to sort, I had issues both with the supplied dicomsort and the bidseditor. The fact is that I'm acquired multi-echo MPRAGE data, and the dicomsort doesn't allow me to separate folders for each echo. After fixing that manually, I then tried to organize these data using the bidseditor. When selecting `anat`, however, I see that the echo variable is not available. Not a big deal again, since I could use acq for that, but I figured I'd reach out and report.

Regards,

Daniel

**Comment by marcelzwiers** [comment]
Hi Daniel :-)

I suppose you used the latest code here on github, right (not pypi I mean)? With dicomsort I sort files using `SeriesNumber` but the next level in the DICOM hierarchy is `AcquisitionNumber` and `InstanceNumber`. How did you solve it?

As for your MEMPRAGE data, well, I can't help that because `echo` is not a valid `T1w` entity key according to the [BIDS specification](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#anatomy-imaging-data)

**Comment by marcelzwiers** [comment]
Have you tried simply leaving all echos in one folder? Because the `bidscoiner` should be able to deal with that and should add the echo-number to the `acq` label itself

**Comment by dangom** [comment]
Hi Marcel,

I actually just use dcm2niix directly on a flat directly so I don't really have a "problem" to solve, I was just playing with the coiner. But in order to do so I sorted using [dicomsort.py](https://github.com/pieper/dicomsort) and called it with

```
dicomsort.py -k -s  $DICOMDIR \
    $OUTPUTDIR/%SeriesNumber-%SeriesDescription-%EchoNumbers/%ProtocolName-%InstanceNumber.dcm
```

That made it such that the mapper automatically detected the echoes. With all echoes in a folder I didn't see options to fix the naming, but I didn't know that the coiner would add echo-numbers to the acq label itself.
I'll give it a try again next time I collect data!

Regards,

Daniel
