### ISSUE TITLE
Develop more unit tests

### ISSUE THREAD

**Issue by marcelzwiers** [Donders-Institute/bidscoin#78]
The title says it all. There is already a tox testing framework in bidscoin, but it is underdeveloped and outdated

**Comment by yjmantilla** [comment]
Is it possible to create DICOM / PAR datasets with dummy information in a controlled manner. For sovabids tests I implemented a function that made a dummy EEG dataset in vhdr format which helped me doing CI tests without large file downloads. And since I manually set up its properties I can test stuff I'm interested in.



For reference:
https://github.com/yjmantilla/sovabids/blob/07d2646376122a2d07045a7fca6401e3ea637337/sovabids/datasets.py#L105-L181

**Comment by mateuszpawlik** [comment]
Would [Dicom Cookies!](https://github.com/pydicom/dicom-cookies) work? On the other hand, maybe only the BIDS part of the conversion should be tested and not the DICOM to nifti part. Then, I think only different DICOM header information may be needed and this could be generated using for example [pydicom](https://pydicom.github.io/pydicom/stable/old/writing_files.html#writing-dicom-files).

**Comment by marcelzwiers** [comment]
Looks good, that would certainly help. I lack a bit of time to implement these tests :-)

**Comment by mateuszpawlik** [comment]
Could we narrow it down to maybe one, most crucial test, like a sanity check? Or make a list? I don't have much experience and I don't know tox framework.

**Comment by marcelzwiers** [comment]
Sure, any test is welcome. I was thinking of using the tutorial dataset as a test dataset (it already has a raw data folder + a bids reference folder)
