### ISSUE TITLE
Bidsmapper failing on bad zip file... is this recoverable?

### ISSUE THREAD

**Issue by thomshaw92** [Donders-Institute/bidscoin#91]
I had a long running Bidsmapper (with the -i 2 option on) job fail because of a bad zip file in one of the final datasets:

``` 
2021-06-26 00:34:26 - bidscoin - INFO Making temporary copy: /90days/raw_data/STIMMRI_raw/sub-125/ses-02 -> /tmp/tmpuibwyu_1/sub-125/ses-02
2021-06-26 00:40:18 - bidscoin - INFO Unpacking: ._0024_mp2rage_wip925b_0p75mm_uni-den.zip -> /tmp/tmpuibwyu_1/sub-125/ses-02
Traceback (most recent call last):
  File "/opt/miniconda-latest/bin/bidsmapper", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda-latest/lib/python3.6/site-packages/bidscoin/bidsmapper.py", line 353, in main
    interactive  = args.interactive)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/bidscoin/bidsmapper.py", line 245, in bidsmapper
    session, unpacked = bids.unpack(session, subprefix, sesprefix, '*')
  File "/opt/miniconda-latest/lib/python3.6/site-packages/bidscoin/bids.py", line 383, in unpack
    with zipfile.ZipFile(packedfile, 'r') as zip_fid:
  File "/opt/miniconda-latest/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/opt/miniconda-latest/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```
Followed by a hard crash. 

I can see that the bidsmap.yaml file hasn't been updated - but there is a text document named bidsmapper.txt

Is it possible to recover all the manual work I've done updating the names of the series from this text document? Or is it basically all gone?

**Comment by marcelzwiers** [comment]
I see you are using an older bidscoin version (I removed the `-i 2` option because it added complexity and I thought nobody would use it), but most likely that doesn't make a difference because the reading and writing of zipfiles is done by external libraries. So if your zipfile is corrupt, there is, unfortunately nothing bidscoin can do about it, and the crash is indeed unfortunate because bidscoin writes the bidsmap only at the end. I don't know what the `bidsmapper.txt` file is, I think I didn't program that?

**Comment by thomshaw92** [comment]
Oh, that's unfortunate. 
I had unzipped all of the files first, but there was a broken zip file left over that caused the crash.
This is the bidsmapper.txt file: 

![capture2](https://user-images.githubusercontent.com/31721414/123568565-f2836480-d807-11eb-9cef-f74fe5186057.PNG)

I wonder if there might be a way of recovering the changes that I made to the bidsmap.yaml while it was running? Does the bidsmap.yaml file update based on the text file? Or is there a record of the changes I made? 
Thanks again for your help.

**Comment by marcelzwiers** [comment]
That txt-file is the logfile (which should have a `.log` extension instead of a `.txt`?) and you will find all the changes you made, but there is no way to recover your edits from it and add them to the yaml file (only with a lot of work). But did you have so many edits? Because re-running the bidsmapper should have only given you new / unknown runs and that list should normally be pretty short?

**Comment by thomshaw92** [comment]
We unfortunately had a scanner software upgrade mid-project and all of our runs have changed. So there were many bespoke scans and weird naming conventions used while things started back up. 
I will try re-running the bidsmapper and see how it goes with the dccn template.
