### ISSUE TITLE
Attributes in bidseditor being deleted

### ISSUE THREAD

**Issue by YohanWards** [Donders-Institute/bidscoin#93]
Hey, each time I change the suffix or the data type in bidseditor the attributes get deleted (see screenshots).
Will this affect the metadata/json file on output at all? If so, is it possible to fix this?
Really appreciate any help

<img width="1286" alt="originalSuffix" src="https://user-images.githubusercontent.com/51389963/123917135-cc0b2800-d9c5-11eb-877d-2711c0b81f7d.png">
<img width="1288" alt="changedSuffix" src="https://user-images.githubusercontent.com/51389963/123917158-d2010900-d9c5-11eb-9774-e1477ce98428.png">

**Comment by marcelzwiers** [comment]
Hi there,

Yes, this is a bit unfortunate but also was hard to fix in the past releases (that's why I set the tooltip helptext to be something like "Please select the datatype and suffix first"). The problem in transferring the entities between run-items is that the entities may change (some will go, some will be added). I can try to transfer data between the entities that remain, because in my latest code this is now easier to do. Some data loss can still happen of course (when entities are not present for the new suffix), but it's better than nothing :-)

**Comment by marcelzwiers** [comment]
Btw, all your DICOM attributes are empty in your lower screenshot? How is that even possible? And pretty cool to see this working on a mac, I've never tried that or seen screenshots of it :-)

**Comment by marcelzwiers** [comment]
And to answer your question, this will not effect the json/meta data, the json's are generated during bidscoiner runtime, and the the data in the meta-data table is then added to the json

**Comment by YohanWards** [comment]
Yea that's the problem, as soon as I change the suffix or select a different data type the attributes field gets completely cleared.
But that's great to know that it won't affect the json so I guess it doesn't really matter, thank you! 
It works very well on a mac :)

**Comment by marcelzwiers** [comment]
The DICOM attributes get cleared or the bids entities? The bids entities I know, but if the DICOM attributes get cleared, then that's a bug I should fix

**Comment by YohanWards** [comment]
Yea the DICOM attributes get wiped. The two screen shots above are before and after changing the suffix. Before changing the suffix all the attributes are present and then I change the suffix and the attributes all disappear. The same thing happens when changing the data type

**Comment by marcelzwiers** [comment]
I cannot reproduce this using my normal test routine, so I need some more info from you:
- Did you move your data between running the bidsmapper and the bidseditor (probably not, but I need to know)? It seems that the data was found before (see the `path` and `name` fields), but the `size` and `nrfiles` are empty, I guess because the bidseditor can't find the data anymore
- Did you have a DICOMDIR or zipped data as input?
- I see a lot of run-items that are set `excluded`, having many `None`'s due to missing DICOM attributes? This is not typical, was your data (heavily) anonymized?

**Comment by marcelzwiers** [comment]
Were there any warnings or errors in the terminal? (you can also find them back in your `bidsfolder/code/bidscoin/bidsmapper.log` file)

**Comment by marcelzwiers** [comment]
If I'm correct in that your source data is not there, and this is something that you cannot avoid, then you can solve it by storing a few sample files using the `bidsmapper -s` option

**Comment by YohanWards** [comment]
Hi Marcel,
I am editing the bidsmapper in a different location to the data (it is on a physical disk somewhere else, and I wanted to do some editing offline). I have just checked, and the bug is gone when I run the bidseditor in the same location as the data. 😊
I was wondering – is it possible to run the bidsmapper again now with the -s option and the -b option set to the bidsmap we have just edited? Will it save the sample data still?
Thanks!

**Comment by marcelzwiers** [comment]
Yes, that could in principle work, but not with the `-b` but with the `-t` option (the bidsmapper always re-uses your existing bidsmap, the `-b` is there in case you want to use a different bidsmap -- a rare/hypothetical use case that I have never used myself). The bidsmapper stores one example source file in `bidsfolder/code/bidscoin` for each new run-item (source datatype) it encounters, i.e. that is not yet in the bidsmap. So what you need to do is e.g. rename your `bidsmap.yaml` file to e.g. `bidsmap_temp.yaml` and then run the bidsmapper with `-t bidsfolder/code/bidscoin/bidsmap_temp`.
